# fly.toml app configuration file generated for lirenda on 2023-04-21T01:27:59+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "x-docker-lidada"
primary_region = "ams"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
PORT = "7860"
UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/dashboard/data"
  source = "nz_data"
  
[[services]]
protocol = "tcp"
internal_port = 7860
processes = ["app"]

[[services.ports]]
port = 7860
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "15s"
timeout = "2s"
grace_period = "1s"
restart_limit = 0
